### ISSUE TITLE
Install Instructions Did Not Work

### ISSUE THREAD

**Issue by Danbana** [ainame/fastlane-plugin-frameit_rtl_support#1]
The line:
fastlane add_plugin frameit_rtl_support

gave:
[19:11:23]: Seems like the plugin is not available on RubyGems, what do you want to do?
1. Git URL
2. Local Path
3. RubyGems.org ('fastlane-plugin-frameit_rtl_support' seems to not be available there)
4. Other Gem Server

Great idea though, I can't believe Arabic doesn't work correctly in frameit!

**Comment by ainame** [comment]
Well, this is an experiment and that instruction would be just a template text generated by bundler. I don't plan to publish this gem to rubygems.org. Thank you for giving it a try though. I ended up doing a different approach. I may write up a blog about how to do that and leave a link in the issue in Fastlane repo I originally mentioned this gem.

You can set up your project with Gemfile specifying with this git repository directly.
